### ISSUE TITLE
git clone fails due to workspace not getting cleaned up

### ISSUE THREAD

**Issue by leifmadsen** [redhat-nfvpe/ansible-cira#36]
[oooq-master-deploy-cira] $ /bin/sh -xe /tmp/hudson1628550700071820413.sh
- git clone https://git.openstack.org/openstack/tripleo-quickstart.git
  fatal: destination path 'tripleo-quickstart' already exists and is not an empty directory.
  Build step 'Execute shell' marked build as failure

**Comment by redhat-nfvpe** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;a1MQL3Hi&#x2F;108-bug-git-clone-fails-due-to-workspace-not-getting-cleaned-up"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> [BUG] git clone fails due to workspace not getting cleaned up</a>

**Comment by leifmadsen** [comment]
Resolved in b686f1eedc3c12ed9f18a3d64feebefaf3062426
